name: Python App CI

on:
  workflow_dispatch:       # Allows manual trigger from dashboard (IMPORTANT!)
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Dummy Test
      run: echo "All tests passed!"

    - name: Log Build Result
  run: |
    curl -X POST https://cicdvisualizer-production.up.railway.app/api/log-build \
         -H "Content-Type: application/json" \
         -d '{
               "workflow_name": "Python App CI",
               "run_id": ${{ github.run_id }},
               "status": "completed",
               "conclusion": "${{ job.status }}",
               "triggered_by": "manual"
             }'

